### ISSUE TITLE
Remove experiment-tracking topic label from the project

### ISSUE THREAD

**Issue by zhimin-z** [scicloj/scicloj.ml#12]
This project aims not for an experiment-tracking tool, I wonder if the repo holder minds tweaking the topic labels a bit.

**Comment by behrica** [comment]
Thanks for the comment.
The experiment-tracking tag is based on a existing call back mechanism in `scicloj.ml
which could be used by anybody to implement experiment tracking.

So it is correct to say:

'Open to pluggable ML experiment tracking'.

Maybe we can change the wording to make this more clear.
The tutorial here:
https://scicloj.github.io/scicloj.ml-tutorials/userguide-experiment-tracking.html

says very little on this, it's true.


My personal opinion is, that implement proper experiment tracking is a lot of work, so I have not considered starting this.

**Comment by behrica** [comment]
I changed the text here, to make it more clear:

https://github.com/scicloj/scicloj.ml/blob/main/README.md

Thanks for feedback.
